/* Ordbankar for mengdetrening (Del 2 · Mengdetrening).
   Drills (js/drills.js) lagar mange små oppgåver ut frå desse tabellane.

   Skrivemåte:
   - Alternative former som begge er rette, skriv du med | i same streng: "gav|ga".
   - bm er bokmålsforma. Ho blir brukt til «kva heiter … på nynorsk» og som distraktor.
     Sløyf bm når ordet er likt på bokmål.
   - Alle former skal følgje gjeldande nynorsknorm (2012). Er du usikker: sjekk Nynorskordboka.

   nouns:      { w, g: "m"|"f"|"n", f: [ubest.eintal, best.eintal, ubest.fleirtal, best.fleirtal], bm? }
   verbs:      { inf, cls: "a"|"e"|"j"|"kort"|"sterk"|"u", f: [presens, preteritum, perfektum partisipp], bm? }
   adjectives: { w, f: { n, pl, komp, sup }, bm? }      (w = grunnform; pl brukast òg for bestemt form)
   words:      { bm, nn: "ikkje", wrong?: ["ikje"], cue?: "…", why?: "…", tags?: ["sporjeord"] }
   sentences:  { setnamn: [ { prompt: "Eg såg ___ i går.", cue: "(ho/henne)", accept: ["henne"], options?: [...], why: "…" } ] }
*/

const Bank = {};

/* ---------------- SUBSTANTIV ---------------- */
Bank.nouns = [
  // Hankjønn, regelrette (-en, -ar, -ane)
  { w: "gut",    g: "m", f: ["gut", "guten", "gutar", "gutane"], bm: "gutt" },
  { w: "bil",    g: "m", f: ["bil", "bilen", "bilar", "bilane"] },
  { w: "stol",   g: "m", f: ["stol", "stolen", "stolar", "stolane"] },
  { w: "hund",   g: "m", f: ["hund", "hunden", "hundar", "hundane"] },
  { w: "skog",   g: "m", f: ["skog", "skogen", "skogar", "skogane"] },
  { w: "båt",    g: "m", f: ["båt", "båten", "båtar", "båtane"] },
  { w: "hest",   g: "m", f: ["hest", "hesten", "hestar", "hestane"] },
  { w: "stein",  g: "m", f: ["stein", "steinen", "steinar", "steinane"] },
  { w: "dag",    g: "m", f: ["dag", "dagen", "dagar", "dagane"] },
  { w: "fisk",   g: "m", f: ["fisk", "fisken", "fiskar", "fiskane"] },
  { w: "katt",   g: "m", f: ["katt", "katten", "kattar", "kattane"] },
  { w: "kopp",   g: "m", f: ["kopp", "koppen", "koppar", "koppane"] },
  { w: "veg",    g: "m", f: ["veg", "vegen", "vegar", "vegane"], bm: "vei" },
  { w: "by",     g: "m", f: ["by", "byen", "byar", "byane"] },
  { w: "fugl",   g: "m", f: ["fugl", "fuglen", "fuglar", "fuglane"] },
  { w: "song",   g: "m", f: ["song", "songen", "songar", "songane"], bm: "sang" },
  { w: "draum",  g: "m", f: ["draum", "draumen", "draumar", "draumane"], bm: "drøm" },
  { w: "straum", g: "m", f: ["straum", "straumen", "straumar", "straumane"], bm: "strøm" },
  { w: "heim",   g: "m", f: ["heim", "heimen", "heimar", "heimane"], bm: "hjem" },
  { w: "bekk",   g: "m", f: ["bekk", "bekken", "bekkar", "bekkane"] },
  { w: "kniv",   g: "m", f: ["kniv", "kniven", "knivar", "knivane"] },
  { w: "ball",   g: "m", f: ["ball", "ballen", "ballar", "ballane"] },
  { w: "elev",   g: "m", f: ["elev", "eleven", "elevar", "elevane"] },
  { w: "lærar",  g: "m", f: ["lærar", "læraren", "lærarar", "lærarane"], bm: "lærer" },
  { w: "bakke",  g: "m", f: ["bakke", "bakken", "bakkar", "bakkane"] },
  { w: "hage",   g: "m", f: ["hage", "hagen", "hagar", "hagane"] },
  { w: "time",   g: "m", f: ["time", "timen", "timar", "timane"] },
  { w: "måne",   g: "m", f: ["måne", "månen", "månar", "månane"] },
  { w: "pose",   g: "m", f: ["pose", "posen", "posar", "posane"] },
  { w: "skule",  g: "m", f: ["skule", "skulen", "skular", "skulane"], bm: "skole" },
  { w: "nase",   g: "m", f: ["nase", "nasen", "nasar", "nasane"], bm: "nese" },
  // Hankjønn, uregelrette
  { w: "gjest",  g: "m", f: ["gjest", "gjesten", "gjester", "gjestene"] },
  { w: "stad",   g: "m", f: ["stad", "staden", "stader", "stadene"], bm: "sted" },
  { w: "bonde",  g: "m", f: ["bonde", "bonden", "bønder", "bøndene"] },
  { w: "fot",    g: "m", f: ["fot", "foten", "føter", "føtene"] },
  { w: "mann",   g: "m", f: ["mann", "mannen", "menn", "mennene"] },
  { w: "bror",   g: "m", f: ["bror", "broren", "brør", "brørne"] },
  { w: "far",    g: "m", f: ["far", "faren", "fedrar", "fedrane"] },
  { w: "son",    g: "m", f: ["son", "sonen", "søner", "sønene"], bm: "sønn" },
  { w: "sommar", g: "m", f: ["sommar", "sommaren", "somrar", "somrane"], bm: "sommer" },
  { w: "vinter", g: "m", f: ["vinter", "vinteren", "vintrar", "vintrane"] },
  { w: "finger", g: "m", f: ["finger", "fingeren", "fingrar", "fingrane"] },
  { w: "sykkel", g: "m", f: ["sykkel", "sykkelen", "syklar", "syklane"] },

  // Hokjønn, regelrette (-a, -er, -ene)
  { w: "jente",  g: "f", f: ["jente", "jenta", "jenter", "jentene"] },
  { w: "klokke", g: "f", f: ["klokke", "klokka", "klokker", "klokkene"] },
  { w: "sol",    g: "f", f: ["sol", "sola", "soler", "solene"] },
  { w: "dør",    g: "f", f: ["dør", "døra", "dører", "dørene"] },
  { w: "bygd",   g: "f", f: ["bygd", "bygda", "bygder", "bygdene"] },
  { w: "veke",   g: "f", f: ["veke", "veka", "veker", "vekene"], bm: "uke" },
  { w: "kyrkje", g: "f", f: ["kyrkje", "kyrkja", "kyrkjer", "kyrkjene"], bm: "kirke" },
  { w: "avis",   g: "f", f: ["avis", "avisa", "aviser", "avisene"] },
  { w: "bru",    g: "f", f: ["bru", "brua", "bruer", "bruene"], bm: "bro" },
  { w: "seng",   g: "f", f: ["seng", "senga", "senger", "sengene"] },
  { w: "vogn",   g: "f", f: ["vogn", "vogna", "vogner", "vognene"] },
  { w: "flaske", g: "f", f: ["flaske", "flaska", "flasker", "flaskene"] },
  { w: "kake",   g: "f", f: ["kake", "kaka", "kaker", "kakene"] },
  { w: "jakke",  g: "f", f: ["jakke", "jakka", "jakker", "jakkene"] },
  { w: "lampe",  g: "f", f: ["lampe", "lampa", "lamper", "lampene"] },
  { w: "gate",   g: "f", f: ["gate", "gata", "gater", "gatene"] },
  { w: "side",   g: "f", f: ["side", "sida", "sider", "sidene"] },
  { w: "helg",   g: "f", f: ["helg", "helga", "helger", "helgene"] },
  { w: "høne",   g: "f", f: ["høne", "høna", "høner", "hønene"] },
  { w: "geit",   g: "f", f: ["geit", "geita", "geiter", "geitene"] },
  { w: "bjørk",  g: "f", f: ["bjørk", "bjørka", "bjørker", "bjørkene"] },
  { w: "grein",  g: "f", f: ["grein", "greina", "greiner", "greinene"], bm: "gren" },
  { w: "øks",    g: "f", f: ["øks", "øksa", "økser", "øksene"] },
  { w: "hytte",  g: "f", f: ["hytte", "hytta", "hytter", "hyttene"] },
  { w: "ferje",  g: "f", f: ["ferje", "ferja", "ferjer", "ferjene"], bm: "ferge" },
  { w: "tid",    g: "f", f: ["tid", "tida", "tider", "tidene"] },
  { w: "nål",    g: "f", f: ["nål", "nåla", "nåler", "nålene"] },
  // Hokjønn, uregelrette (omlyd, -ar)
  { w: "bok",    g: "f", f: ["bok", "boka", "bøker", "bøkene"] },
  { w: "natt",   g: "f", f: ["natt", "natta", "netter", "nettene"] },
  { w: "hand",   g: "f", f: ["hand", "handa", "hender", "hendene"], bm: "hånd" },
  { w: "strand", g: "f", f: ["strand", "stranda", "strender", "strendene"] },
  { w: "tann",   g: "f", f: ["tann", "tanna", "tenner", "tennene"] },
  { w: "ku",     g: "f", f: ["ku", "kua", "kyr", "kyrne"] },
  { w: "mor",    g: "f", f: ["mor", "mora", "mødrer", "mødrene"] },
  { w: "dotter", g: "f", f: ["dotter", "dottera", "døtrer", "døtrene"], bm: "datter" },
  { w: "syster", g: "f", f: ["syster", "systera", "systrer", "systrene"], bm: "søster" },
  { w: "øy",     g: "f", f: ["øy", "øya", "øyar", "øyane"] },
  { w: "elv",    g: "f", f: ["elv", "elva", "elvar", "elvane"] },
  { w: "myr",    g: "f", f: ["myr", "myra", "myrar", "myrane"] },

  // Inkjekjønn, sterke (inga ending i fleirtal, -a i bestemt fleirtal)
  { w: "hus",    g: "n", f: ["hus", "huset", "hus", "husa"] },
  { w: "tre",    g: "n", f: ["tre", "treet", "tre", "trea"] },
  { w: "år",     g: "n", f: ["år", "året", "år", "åra"] },
  { w: "bord",   g: "n", f: ["bord", "bordet", "bord", "borda"] },
  { w: "brev",   g: "n", f: ["brev", "brevet", "brev", "breva"] },
  { w: "fjell",  g: "n", f: ["fjell", "fjellet", "fjell", "fjella"] },
  { w: "land",   g: "n", f: ["land", "landet", "land", "landa"] },
  { w: "ord",    g: "n", f: ["ord", "ordet", "ord", "orda"] },
  { w: "glas",   g: "n", f: ["glas", "glaset", "glas", "glasa"], bm: "glass" },
  { w: "dyr",    g: "n", f: ["dyr", "dyret", "dyr", "dyra"] },
  { w: "bein",   g: "n", f: ["bein", "beinet", "bein", "beina"], bm: "ben" },
  { w: "blad",   g: "n", f: ["blad", "bladet", "blad", "blada"] },
  { w: "egg",    g: "n", f: ["egg", "egget", "egg", "egga"] },
  { w: "hår",    g: "n", f: ["hår", "håret", "hår", "håra"] },
  { w: "skip",   g: "n", f: ["skip", "skipet", "skip", "skipa"] },
  { w: "tak",    g: "n", f: ["tak", "taket", "tak", "taka"] },
  { w: "lys",    g: "n", f: ["lys", "lyset", "lys", "lysa"] },
  { w: "skap",   g: "n", f: ["skap", "skapet", "skap", "skapa"] },
  { w: "vatn",   g: "n", f: ["vatn", "vatnet", "vatn", "vatna"], bm: "vann" },
  { w: "kne",    g: "n", f: ["kne", "kneet", "kne", "knea"] },
  { w: "fly",    g: "n", f: ["fly", "flyet", "fly", "flya"] },
  { w: "namn",   g: "n", f: ["namn", "namnet", "namn", "namna"], bm: "navn" },
  { w: "hjul",   g: "n", f: ["hjul", "hjulet", "hjul", "hjula"] },
  { w: "kjøkken",  g: "n", f: ["kjøkken", "kjøkkenet", "kjøkken", "kjøkkena"] },
  { w: "spørsmål", g: "n", f: ["spørsmål", "spørsmålet", "spørsmål", "spørsmåla"] },
  { w: "problem",  g: "n", f: ["problem", "problemet", "problem", "problema"] },
  { w: "barn",   g: "n", f: ["barn", "barnet", "barn|born", "barna|borna"] },
  // Inkjekjønn, svake (endar på -e)
  { w: "eple",     g: "n", f: ["eple", "eplet", "eple", "epla"] },
  { w: "hjarte",   g: "n", f: ["hjarte", "hjartet", "hjarte", "hjarta"], bm: "hjerte" },
  { w: "vindauge", g: "n", f: ["vindauge", "vindauget", "vindauge", "vindauga"], bm: "vindu" },
  { w: "bilete",   g: "n", f: ["bilete", "biletet", "bilete", "bileta"], bm: "bilde" },
  { w: "stykke",   g: "n", f: ["stykke", "stykket", "stykke", "stykka"] },
  { w: "rike",     g: "n", f: ["rike", "riket", "rike", "rika"] },
  { w: "auge",     g: "n", f: ["auge", "auget", "auge|augo", "auga|augo"], bm: "øye" },
];

/* ---------------- VERB ---------------- */
Bank.verbs = [
  // a-verb
  { inf: "kaste",  cls: "a", f: ["kastar", "kasta", "kasta"] },
  { inf: "hoppe",  cls: "a", f: ["hoppar", "hoppa", "hoppa"] },
  { inf: "snakke", cls: "a", f: ["snakkar", "snakka", "snakka"] },
  { inf: "vente",  cls: "a", f: ["ventar", "venta", "venta"] },
  { inf: "elske",  cls: "a", f: ["elskar", "elska", "elska"] },
  { inf: "lage",   cls: "a", f: ["lagar", "laga", "laga"] },
  { inf: "spele",  cls: "a", f: ["spelar", "spela", "spela"], bm: "spille" },
  { inf: "danse",  cls: "a", f: ["dansar", "dansa", "dansa"] },
  { inf: "bade",   cls: "a", f: ["badar", "bada", "bada"] },
  { inf: "hente",  cls: "a", f: ["hentar", "henta", "henta"] },
  // e-verb
  { inf: "høyre",  cls: "e", f: ["høyrer", "høyrde", "høyrt"], bm: "høre" },
  { inf: "lære",   cls: "e", f: ["lærer", "lærte", "lært"] },
  { inf: "kjøpe",  cls: "e", f: ["kjøper", "kjøpte", "kjøpt"] },
  { inf: "reise",  cls: "e", f: ["reiser", "reiste", "reist"] },
  { inf: "køyre",  cls: "e", f: ["køyrer", "køyrde", "køyrt"], bm: "kjøre" },
  { inf: "tenkje|tenke", cls: "e", f: ["tenkjer|tenker", "tenkte", "tenkt"], bm: "tenke" },
  { inf: "leve",   cls: "e", f: ["lever", "levde", "levd"] },
  // j-verb
  { inf: "spørje", cls: "j", f: ["spør", "spurde", "spurt"], bm: "spørre" },
  { inf: "telje",  cls: "j", f: ["tel", "talde", "talt"], bm: "telle" },
  { inf: "selje",  cls: "j", f: ["sel", "selde", "selt"], bm: "selge" },
  { inf: "setje",  cls: "j", f: ["set", "sette", "sett"], bm: "sette" },
  // kortverb
  { inf: "bu",     cls: "kort", f: ["bur", "budde", "budd"], bm: "bo" },
  { inf: "nå",     cls: "kort", f: ["når", "nådde", "nådd"] },
  { inf: "tru",    cls: "kort", f: ["trur", "trudde", "trudd"], bm: "tro" },
  { inf: "ha",     cls: "kort", f: ["har", "hadde", "hatt"] },
  // sterke verb
  { inf: "skrive", cls: "sterk", f: ["skriv", "skreiv", "skrive"] },
  { inf: "finne",  cls: "sterk", f: ["finn", "fann", "funne"] },
  { inf: "gå",     cls: "sterk", f: ["går", "gjekk", "gått"] },
  { inf: "vere",   cls: "sterk", f: ["er", "var", "vore"], bm: "være" },
  { inf: "sjå",    cls: "sterk", f: ["ser", "såg", "sett"], bm: "se" },
  { inf: "gi|gje", cls: "sterk", f: ["gir|gjev", "gav|ga", "gitt|gjeve"] },
  { inf: "komme|kome", cls: "sterk", f: ["kjem", "kom", "kome|komme"] },
  { inf: "ete",    cls: "sterk", f: ["et", "åt", "ete"], bm: "spise" },
  { inf: "drikke", cls: "sterk", f: ["drikk", "drakk", "drukke"] },
  { inf: "synge",  cls: "sterk", f: ["syng", "song", "sunge"] },
  { inf: "springe", cls: "sterk", f: ["spring", "sprang", "sprunge"], bm: "løpe" },
  { inf: "bite",   cls: "sterk", f: ["bit", "beit", "bite"] },
  { inf: "fryse",  cls: "sterk", f: ["frys", "fraus", "frose"] },
  { inf: "lese",   cls: "sterk", f: ["les", "las", "lese"] },
  { inf: "sitje",  cls: "sterk", f: ["sit", "sat", "sete"], bm: "sitte" },
  { inf: "liggje", cls: "sterk", f: ["ligg", "låg", "lege"], bm: "ligge" },
  { inf: "ta",     cls: "sterk", f: ["tek|tar", "tok", "teke|tatt"] },
  { inf: "sove",   cls: "sterk", f: ["søv", "sov", "sove"] },
  { inf: "bere",   cls: "sterk", f: ["ber", "bar", "bore"], bm: "bære" },
  // uregelrette svake verb
  { inf: "seie",   cls: "u", f: ["seier", "sa", "sagt"], bm: "si" },
  { inf: "gjere",  cls: "u", f: ["gjer", "gjorde", "gjort"], bm: "gjøre" },
  { inf: "vite",   cls: "u", f: ["veit", "visste", "visst"] },
];

/* ---------------- ADJEKTIV ---------------- */
Bank.adjectives = [
  { w: "fin",    f: { n: "fint", pl: "fine", komp: "finare", sup: "finast" } },
  { w: "stor",   f: { n: "stort", pl: "store", komp: "større", sup: "størst" } },
  { w: "god",    f: { n: "godt", pl: "gode", komp: "betre", sup: "best" } },
  { w: "liten",  f: { n: "lite", pl: "små", komp: "mindre", sup: "minst" } },
  { w: "gammal", f: { n: "gammalt", pl: "gamle", komp: "eldre", sup: "eldst" }, bm: "gammel" },
  { w: "ung",    f: { n: "ungt", pl: "unge", komp: "yngre", sup: "yngst" } },
  { w: "lang",   f: { n: "langt", pl: "lange", komp: "lengre", sup: "lengst" } },
  { w: "høg",    f: { n: "høgt", pl: "høge", komp: "høgare", sup: "høgast" }, bm: "høy" },
  { w: "ny",     f: { n: "nytt", pl: "nye", komp: "nyare", sup: "nyast" } },
  { w: "rask",   f: { n: "raskt", pl: "raske", komp: "raskare", sup: "raskast" } },
  { w: "billeg", f: { n: "billeg", pl: "billege", komp: "billegare", sup: "billegast" }, bm: "billig" },
  { w: "vanleg", f: { n: "vanleg", pl: "vanlege", komp: "vanlegare", sup: "vanlegast" }, bm: "vanlig" },
  { w: "varm",   f: { n: "varmt", pl: "varme", komp: "varmare", sup: "varmast" } },
  { w: "kald",   f: { n: "kaldt", pl: "kalde", komp: "kaldare", sup: "kaldast" } },
  { w: "raud",   f: { n: "raudt", pl: "raude", komp: "raudare", sup: "raudast" }, bm: "rød" },
  { w: "grøn",   f: { n: "grønt", pl: "grøne", komp: "grønare", sup: "grønast" }, bm: "grønn" },
  { w: "brei",   f: { n: "breitt", pl: "breie", komp: "breiare", sup: "breiast" }, bm: "bred" },
  { w: "stygg",  f: { n: "stygt", pl: "stygge", komp: "styggare", sup: "styggast" } },
  { w: "snill",  f: { n: "snilt", pl: "snille", komp: "snillare", sup: "snillast" } },
  { w: "tung",   f: { n: "tungt", pl: "tunge", komp: "tyngre", sup: "tyngst" } },
  { w: "lett",   f: { n: "lett", pl: "lette", komp: "lettare", sup: "lettast" } },
  { w: "sterk",  f: { n: "sterkt", pl: "sterke", komp: "sterkare", sup: "sterkast" } },
  { w: "mjuk",   f: { n: "mjukt", pl: "mjuke", komp: "mjukare", sup: "mjukast" }, bm: "myk" },
  { w: "trøytt", f: { n: "trøytt", pl: "trøytte", komp: "trøyttare", sup: "trøyttast" }, bm: "trøtt" },
  { w: "sein",   f: { n: "seint", pl: "seine", komp: "seinare", sup: "seinast" }, bm: "sen" },
  { w: "tidleg", f: { n: "tidleg", pl: "tidlege", komp: "tidlegare", sup: "tidlegast" }, bm: "tidlig" },
  { w: "djup",   f: { n: "djupt", pl: "djupe", komp: "djupare", sup: "djupast" }, bm: "dyp" },
  { w: "låg",    f: { n: "lågt", pl: "låge", komp: "lågare", sup: "lågast" }, bm: "lav" },
  { w: "mørk",   f: { n: "mørkt", pl: "mørke", komp: "mørkare", sup: "mørkast" } },
  { w: "dyr",    f: { n: "dyrt", pl: "dyre", komp: "dyrare", sup: "dyrast" } },
  { w: "rik",    f: { n: "rikt", pl: "rike", komp: "rikare", sup: "rikast" } },
  { w: "fattig", f: { n: "fattig", pl: "fattige", komp: "fattigare", sup: "fattigast" } },
  { w: "heil",   f: { n: "heilt", pl: "heile", komp: "heilare", sup: "heilast" }, bm: "hel" },
  { w: "open",   f: { n: "ope", pl: "opne", komp: "opnare", sup: "opnast" }, bm: "åpen" },
];

/* ---------------- SMÅORD (bokmål → nynorsk) ---------------- */
Bank.words = [
  { bm: "ikke",      nn: "ikkje",  wrong: ["ikje", "ike"], tags: ["smaord"] },
  { bm: "bare",      nn: "berre",  wrong: ["bere", "barre"], tags: ["smaord"] },
  { bm: "hva",       nn: "kva",    wrong: ["ka", "kvad"], tags: ["sporjeord"] },
  { bm: "hvem",      nn: "kven",   wrong: ["kvem", "kem"], tags: ["sporjeord"] },
  { bm: "hvor",      nn: "kvar",   cue: "(om stad: hvor bor du?)", wrong: ["kor", "kvor"], tags: ["sporjeord"], why: "<em class=\"nn\">kvar</em> spør om stad («Kvar bur du?»), <em class=\"nn\">kor</em> spør om grad eller mengd («Kor gammal er du?»)." },
  { bm: "hvor",      nn: "kor",    cue: "(om grad: hvor gammel er du?)", wrong: ["kvar", "kvor"], tags: ["sporjeord"], why: "<em class=\"nn\">kor</em> spør om grad eller mengd («Kor gammal er du?»), <em class=\"nn\">kvar</em> spør om stad." },
  { bm: "hvordan",   nn: "korleis", wrong: ["kordan", "kvordan"], tags: ["sporjeord"] },
  { bm: "hvorfor",   nn: "kvifor", wrong: ["kvorfor", "korfor"], tags: ["sporjeord"] },
  { bm: "hvilken",   nn: "kva for ein|kva for", wrong: ["kvilken", "kven"], tags: ["sporjeord"] },
  { bm: "fra",       nn: "frå",    wrong: ["fra", "fraa"], tags: ["smaord"] },
  { bm: "mye",       nn: "mykje",  wrong: ["mye", "myke"], tags: ["smaord"] },
  { bm: "noe",       nn: "noko",   wrong: ["nokon", "noe"], tags: ["smaord"] },
  { bm: "jeg",       nn: "eg",     wrong: ["e", "jeg"], tags: ["pronomen"] },
  { bm: "hun",       nn: "ho",     wrong: ["hun", "hu"], tags: ["pronomen"] },
  { bm: "dem",       nn: "dei",    wrong: ["dem", "de"], tags: ["pronomen"] },
  { bm: "dere",      nn: "de|dokker", cue: "(som subjekt: dere kommer)", wrong: ["dykk", "dere"], tags: ["pronomen"] },
  { bm: "vi",        nn: "vi|me",  wrong: ["oss"], tags: ["pronomen"] },
  { bm: "også",      nn: "også|òg", wrong: ["og", "ogso"], tags: ["smaord"] },
  { bm: "sammen",    nn: "saman",  wrong: ["sammen", "samen"], tags: ["smaord"] },
  { bm: "hverandre", nn: "kvarandre", wrong: ["kverandre", "hverandre"], tags: ["pronomen"] },
  { bm: "hvis",      nn: "viss|dersom|om", wrong: ["kvis", "hvis"], tags: ["smaord"] },
  { bm: "selv",      nn: "sjølv",  wrong: ["sjøl", "selv"], tags: ["smaord"] },
  { bm: "annerledes", nn: "annleis", wrong: ["annerleis", "anleis"], tags: ["smaord"] },
  { bm: "da",        nn: "då",     wrong: ["da", "so"], tags: ["smaord"] },
  { bm: "siden",     nn: "sidan",  wrong: ["siden", "sida"], tags: ["smaord"] },
  { bm: "ennå",      nn: "enno|endå", wrong: ["ennå", "ennu"], tags: ["smaord"] },
  { bm: "mer",       nn: "meir",   wrong: ["mer", "mere"], tags: ["smaord"] },
  { bm: "flere",     nn: "fleire", wrong: ["flere", "fleir"], tags: ["smaord"] },
  { bm: "igjen",     nn: "igjen|att", wrong: ["igjenn"], tags: ["smaord"] },
  { bm: "hjemme",    nn: "heime",  wrong: ["hjemme", "heima"], tags: ["smaord"] },
  { bm: "hver",      nn: "kvar",   cue: "(hver dag)", wrong: ["kver", "hver"], tags: ["smaord"] },
  { bm: "hvert",     nn: "kvart",  cue: "(hvert år)", wrong: ["kvert", "hvert"], tags: ["smaord"] },
  { bm: "uten",      nn: "utan",   wrong: ["uten", "utann"], tags: ["smaord"] },
  { bm: "vanskelig", nn: "vanskeleg", wrong: ["vanskelig", "vanskelegt"], tags: ["adjektiv"] },
  { bm: "dessverre", nn: "diverre|dessverre", wrong: ["desverre"], tags: ["smaord"] },
  { bm: "kjærlighet", nn: "kjærleik", wrong: ["kjærlegheit", "kjærlighet"], tags: ["het"] },
  { bm: "mulighet",  nn: "moglegheit|høve|sjanse", wrong: ["mulegheit", "mulighet"], tags: ["het"] },
  { bm: "sannhet",   nn: "sanning", wrong: ["sannheit", "sannhet"], tags: ["het"] },
  { bm: "frihet",    nn: "fridom",  wrong: ["friheit", "frihet"], tags: ["het"] },
  { bm: "sykdom",    nn: "sjukdom", wrong: ["sykdom", "sjukdomm"], tags: ["diverse"] },
  { bm: "penger",    nn: "pengar",  wrong: ["penger", "pengane"], tags: ["diverse"] },
  { bm: "klær",      nn: "klede",   wrong: ["klær", "kleder"], tags: ["diverse"] },
  { bm: "allerede",  nn: "alt|allereie", wrong: ["allerede", "alereie"], tags: ["smaord"] },
  { bm: "ham",       nn: "han|honom", cue: "(som objekt: jeg så ham)", wrong: ["ham", "hann"], tags: ["pronomen"] },
];

/* ---------------- SETNINGAR (handskrivne) ---------------- */
Bank.sentences = {
  pronomen: [
    { prompt: "Eg såg ___ i går.", cue: "(ho / henne)", accept: ["henne"], options: ["ho"], why: "<em class=\"nn\">henne</em> er objektsform: eg såg <em class=\"nn\">henne</em>." },
    { prompt: "___ kjem i morgon.", cue: "(ho / henne)", accept: ["Ho"], options: ["Henne"], why: "<em class=\"nn\">ho</em> er subjektsform: <em class=\"nn\">ho</em> kjem." },
    { prompt: "Vi såg ___ på kino.", cue: "(dei / dykk)", accept: ["dei"], options: ["dykk", "dem"], why: "<em class=\"nn\">dei</em> er både subjekts- og objektsform i 3. person fleirtal. <em class=\"bm\">dem</em> finst ikkje på nynorsk." },
    { prompt: "Kan ___ hjelpe meg?", cue: "(de / dykk)", accept: ["de", "dokker"], options: ["dykk", "dere"], why: "<em class=\"nn\">de</em> er subjektsform i 2. person fleirtal («Kan de hjelpe meg?»). <em class=\"nn\">dykk</em> er objektsform." },
    { prompt: "Eg skal ringje ___ i kveld.", cue: "(de / dykk)", accept: ["dykk", "dokker"], options: ["de", "dere"], why: "<em class=\"nn\">dykk</em> er objektsform: eg ringjer <em class=\"nn\">dykk</em>." },
    { prompt: "___ er trøytte etter turen.", cue: "(dei / dei)", accept: ["Dei"], options: ["De", "Dem"], why: "<em class=\"nn\">dei</em> = «de/dem» på bokmål. <em class=\"nn\">de</em> på nynorsk tyder «dere»." },
    { prompt: "Har du snakka med ___?", cue: "(han / honom)", accept: ["han", "honom"], options: ["ham"], why: "På nynorsk er <em class=\"nn\">han</em> både subjekts- og objektsform. <em class=\"nn\">honom</em> er òg lov som objekt. <em class=\"bm\">ham</em> er bokmål." },
  ],
  nokon: [
    { prompt: "Er det ___ heime?", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">nokon</em> brukar vi om personar og hankjønnsord i eintal." },
    { prompt: "Vil du ha ___ kaffi?", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "<em class=\"nn\">noko</em> brukar vi om mengd («noko kaffi») og om inkjekjønnsord." },
    { prompt: "Eg har lese ___ bøker i sommar.", cue: "(nokon / noko / nokre)", accept: ["nokre"], options: ["nokon", "noko"], why: "<em class=\"nn\">nokre</em> er fleirtalsforma: nokre bøker." },
    { prompt: "Har du ___ å drikke?", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "<em class=\"nn\">noko</em> brukar vi om «noe» – ei ubestemt mengd eller ein ubestemt ting." },
    { prompt: "Han såg ___ hund i hagen.", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">hund</em> er hankjønn: <em class=\"nn\">nokon</em> hund." },
    { prompt: "Det ligg ___ avis på bordet.", cue: "(noka / noko / nokre)", accept: ["noka", "nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">avis</em> er hokjønn: <em class=\"nn\">noka</em> (eller <em class=\"nn\">nokon</em>) avis." },
  ],
  daNar: [
    { prompt: "___ eg var liten, budde vi i Bergen.", cue: "(då / når)", accept: ["Då"], options: ["Når"], why: "<em class=\"nn\">då</em> om éin gong i fortida: «den gongen då». <em class=\"nn\">når</em> om noko som skjer fleire gonger eller i framtida: «kvar gong når»." },
    { prompt: "___ det regnar, blir eg inne.", cue: "(då / når)", accept: ["Når"], options: ["Då"], why: "Noko som skjer kvar gong: <em class=\"nn\">når</em>." },
    { prompt: "Ring meg ___ du kjem fram.", cue: "(då / når)", accept: ["når"], options: ["då"], why: "Framtid: <em class=\"nn\">når</em>." },
    { prompt: "Vi jubla ___ laget skåra.", cue: "(då / når)", accept: ["då"], options: ["når"], why: "Éin gong i fortida: <em class=\"nn\">då</em>." },
  ],
  kvarKor: [
    { prompt: "___ bur du?", cue: "(kvar / kor)", accept: ["Kvar"], options: ["Kor"], why: "<em class=\"nn\">kvar</em> spør om stad." },
    { prompt: "___ gammal er du?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar"], why: "<em class=\"nn\">kor</em> spør om grad eller mengd." },
    { prompt: "___ mange kjem i kveld?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar"], why: "<em class=\"nn\">kor</em> spør om mengd." },
    { prompt: "Veit du ___ nøklane er?", cue: "(kvar / kor)", accept: ["kvar"], options: ["kor"], why: "<em class=\"nn\">kvar</em> spør om stad." },
  ],
};

if (typeof module !== "undefined" && module.exports) module.exports = Bank;
