/* Ordbankar for mengdetrening (Del 2 · Mengdetrening).
   Drills (js/drills.js) lagar mange små oppgåver ut frå desse tabellane.

   Skrivemåte:
   - Alternative former som begge er rette, skriv du med | i same streng: "gav|ga".
   - bm er bokmålsforma. Ho blir brukt til «kva heiter … på nynorsk» og som distraktor.
     Sløyf bm når ordet er likt på bokmål.
   - Alle former skal følgje gjeldande nynorsknorm (2012). Er du usikker: sjekk Nynorskordboka.

   nouns:      { w, g: "m"|"f"|"n", f: [ubest.eintal, best.eintal, ubest.fleirtal, best.fleirtal], bm? }
   verbs:      { inf, cls: "a"|"e"|"j"|"kort"|"sterk"|"u", f: [presens, preteritum, perfektum partisipp], bm? }
   adjectives: { w, f: { n, pl, komp, sup }, bm? }      (w = grunnform; pl brukast òg for bestemt form)
   words:      { bm, nn: "ikkje", wrong?: ["ikje"], cue?: "…", why?: "…", tags?: ["sporjeord"] }
   sentences:  { setnamn: [ { prompt: "Eg såg ___ i går.", cue: "(ho/henne)", accept: ["henne"], options?: [...], why: "…" } ] }
*/

const Bank = {};

/* ---------------- SUBSTANTIV ---------------- */
Bank.nouns = [
  // Hankjønn, regelrette (-en, -ar, -ane)
  { w: "gut",    g: "m", f: ["gut", "guten", "gutar", "gutane"], bm: "gutt" },
  { w: "bil",    g: "m", f: ["bil", "bilen", "bilar", "bilane"] },
  { w: "stol",   g: "m", f: ["stol", "stolen", "stolar", "stolane"] },
  { w: "hund",   g: "m", f: ["hund", "hunden", "hundar", "hundane"] },
  { w: "skog",   g: "m", f: ["skog", "skogen", "skogar", "skogane"] },
  { w: "båt",    g: "m", f: ["båt", "båten", "båtar", "båtane"] },
  { w: "hest",   g: "m", f: ["hest", "hesten", "hestar", "hestane"] },
  { w: "stein",  g: "m", f: ["stein", "steinen", "steinar", "steinane"] },
  { w: "dag",    g: "m", f: ["dag", "dagen", "dagar", "dagane"] },
  { w: "fisk",   g: "m", f: ["fisk", "fisken", "fiskar", "fiskane"] },
  { w: "katt",   g: "m", f: ["katt", "katten", "kattar", "kattane"] },
  { w: "kopp",   g: "m", f: ["kopp", "koppen", "koppar", "koppane"] },
  { w: "veg",    g: "m", f: ["veg", "vegen", "vegar", "vegane"], bm: "vei" },
  { w: "by",     g: "m", f: ["by", "byen", "byar", "byane"] },
  { w: "fugl",   g: "m", f: ["fugl", "fuglen", "fuglar", "fuglane"] },
  { w: "song",   g: "m", f: ["song", "songen", "songar", "songane"], bm: "sang" },
  { w: "draum",  g: "m", f: ["draum", "draumen", "draumar", "draumane"], bm: "drøm" },
  { w: "straum", g: "m", f: ["straum", "straumen", "straumar", "straumane"], bm: "strøm" },
  { w: "heim",   g: "m", f: ["heim", "heimen", "heimar", "heimane"], bm: "hjem" },
  { w: "bekk",   g: "m", f: ["bekk", "bekken", "bekkar", "bekkane"] },
  { w: "kniv",   g: "m", f: ["kniv", "kniven", "knivar", "knivane"] },
  { w: "ball",   g: "m", f: ["ball", "ballen", "ballar", "ballane"] },
  { w: "elev",   g: "m", f: ["elev", "eleven", "elevar", "elevane"] },
  { w: "lærar",  g: "m", f: ["lærar", "læraren", "lærarar", "lærarane"], bm: "lærer" },
  { w: "bakke",  g: "m", f: ["bakke", "bakken", "bakkar", "bakkane"] },
  { w: "hage",   g: "m", f: ["hage", "hagen", "hagar", "hagane"] },
  { w: "time",   g: "m", f: ["time", "timen", "timar", "timane"] },
  { w: "måne",   g: "m", f: ["måne", "månen", "månar", "månane"] },
  { w: "pose",   g: "m", f: ["pose", "posen", "posar", "posane"] },
  { w: "skule",  g: "m", f: ["skule", "skulen", "skular", "skulane"], bm: "skole" },
  { w: "nase",   g: "m", f: ["nase", "nasen", "nasar", "nasane"], bm: "nese" },
  // Hankjønn, uregelrette
  { w: "gjest",  g: "m", f: ["gjest", "gjesten", "gjester", "gjestene"] },
  { w: "stad",   g: "m", f: ["stad", "staden", "stader", "stadene"], bm: "sted" },
  { w: "bonde",  g: "m", f: ["bonde", "bonden", "bønder", "bøndene"] },
  { w: "fot",    g: "m", f: ["fot", "foten", "føter", "føtene"] },
  { w: "mann",   g: "m", f: ["mann", "mannen", "menn", "mennene"] },
  { w: "bror",   g: "m", f: ["bror", "broren", "brør", "brørne"] },
  { w: "far",    g: "m", f: ["far", "faren", "fedrar", "fedrane"] },
  { w: "son",    g: "m", f: ["son", "sonen", "søner", "sønene"], bm: "sønn" },
  { w: "sommar", g: "m", f: ["sommar", "sommaren", "somrar", "somrane"], bm: "sommer" },
  { w: "vinter", g: "m", f: ["vinter", "vinteren", "vintrar", "vintrane"] },
  { w: "finger", g: "m", f: ["finger", "fingeren", "fingrar", "fingrane"] },
  { w: "sykkel", g: "m", f: ["sykkel", "sykkelen", "syklar", "syklane"] },

  // Hokjønn, regelrette (-a, -er, -ene)
  { w: "jente",  g: "f", f: ["jente", "jenta", "jenter", "jentene"] },
  { w: "klokke", g: "f", f: ["klokke", "klokka", "klokker", "klokkene"] },
  { w: "sol",    g: "f", f: ["sol", "sola", "soler", "solene"] },
  { w: "dør",    g: "f", f: ["dør", "døra", "dører", "dørene"] },
  { w: "bygd",   g: "f", f: ["bygd", "bygda", "bygder", "bygdene"] },
  { w: "veke",   g: "f", f: ["veke", "veka", "veker", "vekene"], bm: "uke" },
  { w: "kyrkje", g: "f", f: ["kyrkje", "kyrkja", "kyrkjer", "kyrkjene"], bm: "kirke" },
  { w: "avis",   g: "f", f: ["avis", "avisa", "aviser", "avisene"] },
  { w: "bru",    g: "f", f: ["bru", "brua", "bruer", "bruene"], bm: "bro" },
  { w: "seng",   g: "f", f: ["seng", "senga", "senger", "sengene"] },
  { w: "vogn",   g: "f", f: ["vogn", "vogna", "vogner", "vognene"] },
  { w: "flaske", g: "f", f: ["flaske", "flaska", "flasker", "flaskene"] },
  { w: "kake",   g: "f", f: ["kake", "kaka", "kaker", "kakene"] },
  { w: "jakke",  g: "f", f: ["jakke", "jakka", "jakker", "jakkene"] },
  { w: "lampe",  g: "f", f: ["lampe", "lampa", "lamper", "lampene"] },
  { w: "gate",   g: "f", f: ["gate", "gata", "gater", "gatene"] },
  { w: "side",   g: "f", f: ["side", "sida", "sider", "sidene"] },
  { w: "helg",   g: "f", f: ["helg", "helga", "helger", "helgene"] },
  { w: "høne",   g: "f", f: ["høne", "høna", "høner", "hønene"] },
  { w: "geit",   g: "f", f: ["geit", "geita", "geiter", "geitene"] },
  { w: "bjørk",  g: "f", f: ["bjørk", "bjørka", "bjørker", "bjørkene"] },
  { w: "grein",  g: "f", f: ["grein", "greina", "greiner", "greinene"], bm: "gren" },
  { w: "øks",    g: "f", f: ["øks", "øksa", "økser", "øksene"] },
  { w: "hytte",  g: "f", f: ["hytte", "hytta", "hytter", "hyttene"] },
  { w: "ferje",  g: "f", f: ["ferje", "ferja", "ferjer", "ferjene"], bm: "ferge" },
  { w: "tid",    g: "f", f: ["tid", "tida", "tider", "tidene"] },
  { w: "nål",    g: "f", f: ["nål", "nåla", "nåler", "nålene"] },
  // Hokjønn, uregelrette (omlyd, -ar)
  { w: "bok",    g: "f", f: ["bok", "boka", "bøker", "bøkene"] },
  { w: "natt",   g: "f", f: ["natt", "natta", "netter", "nettene"] },
  { w: "hand",   g: "f", f: ["hand", "handa", "hender", "hendene"], bm: "hånd" },
  { w: "strand", g: "f", f: ["strand", "stranda", "strender", "strendene"] },
  { w: "tann",   g: "f", f: ["tann", "tanna", "tenner", "tennene"] },
  { w: "ku",     g: "f", f: ["ku", "kua", "kyr", "kyrne"] },
  { w: "mor",    g: "f", f: ["mor", "mora", "mødrer", "mødrene"] },
  { w: "dotter", g: "f", f: ["dotter", "dottera", "døtrer", "døtrene"], bm: "datter" },
  { w: "syster", g: "f", f: ["syster", "systera", "systrer", "systrene"], bm: "søster" },
  { w: "øy",     g: "f", f: ["øy", "øya", "øyar", "øyane"] },
  { w: "elv",    g: "f", f: ["elv", "elva", "elvar", "elvane"] },
  { w: "myr",    g: "f", f: ["myr", "myra", "myrar", "myrane"] },

  // Inkjekjønn, sterke (inga ending i fleirtal, -a i bestemt fleirtal)
  { w: "hus",    g: "n", f: ["hus", "huset", "hus", "husa"] },
  { w: "tre",    g: "n", f: ["tre", "treet", "tre", "trea"] },
  { w: "år",     g: "n", f: ["år", "året", "år", "åra"] },
  { w: "bord",   g: "n", f: ["bord", "bordet", "bord", "borda"] },
  { w: "brev",   g: "n", f: ["brev", "brevet", "brev", "breva"] },
  { w: "fjell",  g: "n", f: ["fjell", "fjellet", "fjell", "fjella"] },
  { w: "land",   g: "n", f: ["land", "landet", "land", "landa"] },
  { w: "ord",    g: "n", f: ["ord", "ordet", "ord", "orda"] },
  { w: "glas",   g: "n", f: ["glas", "glaset", "glas", "glasa"], bm: "glass" },
  { w: "dyr",    g: "n", f: ["dyr", "dyret", "dyr", "dyra"] },
  { w: "bein",   g: "n", f: ["bein", "beinet", "bein", "beina"], bm: "ben" },
  { w: "blad",   g: "n", f: ["blad", "bladet", "blad", "blada"] },
  { w: "egg",    g: "n", f: ["egg", "egget", "egg", "egga"] },
  { w: "hår",    g: "n", f: ["hår", "håret", "hår", "håra"] },
  { w: "skip",   g: "n", f: ["skip", "skipet", "skip", "skipa"] },
  { w: "tak",    g: "n", f: ["tak", "taket", "tak", "taka"] },
  { w: "lys",    g: "n", f: ["lys", "lyset", "lys", "lysa"] },
  { w: "skap",   g: "n", f: ["skap", "skapet", "skap", "skapa"] },
  { w: "vatn",   g: "n", f: ["vatn", "vatnet", "vatn", "vatna"], bm: "vann" },
  { w: "kne",    g: "n", f: ["kne", "kneet", "kne", "knea"] },
  { w: "fly",    g: "n", f: ["fly", "flyet", "fly", "flya"] },
  { w: "namn",   g: "n", f: ["namn", "namnet", "namn", "namna"], bm: "navn" },
  { w: "hjul",   g: "n", f: ["hjul", "hjulet", "hjul", "hjula"] },
  { w: "kjøkken",  g: "n", f: ["kjøkken", "kjøkkenet", "kjøkken", "kjøkkena"] },
  { w: "spørsmål", g: "n", f: ["spørsmål", "spørsmålet", "spørsmål", "spørsmåla"] },
  { w: "problem",  g: "n", f: ["problem", "problemet", "problem", "problema"] },
  { w: "barn",   g: "n", f: ["barn", "barnet", "barn|born", "barna|borna"] },
  // Inkjekjønn, svake (endar på -e)
  { w: "eple",     g: "n", f: ["eple", "eplet", "eple", "epla"] },
  { w: "hjarte",   g: "n", f: ["hjarte", "hjartet", "hjarte", "hjarta"], bm: "hjerte" },
  { w: "vindauge", g: "n", f: ["vindauge", "vindauget", "vindauge", "vindauga"], bm: "vindu" },
  { w: "bilete",   g: "n", f: ["bilete", "biletet", "bilete", "bileta"], bm: "bilde" },
  { w: "stykke",   g: "n", f: ["stykke", "stykket", "stykke", "stykka"] },
  { w: "rike",     g: "n", f: ["rike", "riket", "rike", "rika"] },
  { w: "auge",     g: "n", f: ["auge", "auget", "auge|augo", "auga|augo"], bm: "øye" },
];

/* ---------------- VERB ---------------- */
Bank.verbs = [
  // a-verb (-ar, -a, -a)
  { inf: "kaste",  cls: "a", f: ["kastar", "kasta", "kasta"] },
  { inf: "hoppe",  cls: "a", f: ["hoppar", "hoppa", "hoppa"] },
  { inf: "snakke", cls: "a", f: ["snakkar", "snakka", "snakka"] },
  { inf: "vente",  cls: "a", f: ["ventar", "venta", "venta"] },
  { inf: "elske",  cls: "a", f: ["elskar", "elska", "elska"] },
  { inf: "lage",   cls: "a", f: ["lagar", "laga", "laga"] },
  { inf: "spele",  cls: "a", f: ["spelar", "spela", "spela"], bm: "spille" },
  { inf: "danse",  cls: "a", f: ["dansar", "dansa", "dansa"] },
  { inf: "bade",   cls: "a", f: ["badar", "bada", "bada"] },
  { inf: "hente",  cls: "a", f: ["hentar", "henta", "henta"] },
  { inf: "byrje",  cls: "a", f: ["byrjar", "byrja", "byrja"], bm: "begynne" },
  { inf: "rekne",  cls: "a", f: ["reknar", "rekna", "rekna"], bm: "regne" },
  { inf: "hugse",  cls: "a", f: ["hugsar", "hugsa", "hugsa"], bm: "huske" },
  { inf: "opne",   cls: "a", f: ["opnar", "opna", "opna"], bm: "åpne" },
  { inf: "teikne", cls: "a", f: ["teiknar", "teikna", "teikna"], bm: "tegne" },
  { inf: "svare",  cls: "a", f: ["svarar", "svara", "svara"] },
  { inf: "like",   cls: "a", f: ["likar", "lika", "lika"] },
  { inf: "bruke",  cls: "a", f: ["brukar|bruker", "bruka|brukte", "bruka|brukt"] },
  // e-verb (-er, -de/-te, -d/-t)
  { inf: "høyre",  cls: "e", f: ["høyrer", "høyrde", "høyrt"], bm: "høre" },
  { inf: "lære",   cls: "e", f: ["lærer", "lærte", "lært"] },
  { inf: "kjøpe",  cls: "e", f: ["kjøper", "kjøpte", "kjøpt"] },
  { inf: "reise",  cls: "e", f: ["reiser", "reiste", "reist"] },
  { inf: "køyre",  cls: "e", f: ["køyrer", "køyrde", "køyrt"], bm: "kjøre" },
  { inf: "tenkje|tenke", cls: "e", f: ["tenkjer|tenker", "tenkte", "tenkt"] },
  { inf: "leve",   cls: "e", f: ["lever", "levde", "levd"] },
  { inf: "arbeide", cls: "e", f: ["arbeider", "arbeidde", "arbeidd"] },
  { inf: "kjenne", cls: "e", f: ["kjenner", "kjende", "kjent"] },
  { inf: "vise",   cls: "e", f: ["viser", "viste", "vist"] },
  { inf: "sende",  cls: "e", f: ["sender", "sende", "sendt"] },
  { inf: "hjelpe", cls: "e", f: ["hjelper", "hjelpte", "hjelpt"] },
  { inf: "prøve",  cls: "e", f: ["prøver", "prøvde", "prøvd"] },
  { inf: "møte",   cls: "e", f: ["møter", "møtte", "møtt"] },
  { inf: "meine",  cls: "e", f: ["meiner", "meinte", "meint"], bm: "mene" },
  { inf: "gløyme", cls: "e", f: ["gløymer", "gløymde", "gløymt"], bm: "glemme" },
  { inf: "smile",  cls: "e", f: ["smiler", "smilte", "smilt"] },
  // j-verb (j-en fell bort utanom infinitiv; kj/gj-stammar held på j-en i presens)
  { inf: "spørje", cls: "j", f: ["spør", "spurde", "spurt"], bm: "spørre" },
  { inf: "telje",  cls: "j", f: ["tel", "talde", "talt"], bm: "telle" },
  { inf: "selje",  cls: "j", f: ["sel", "selde", "selt"], bm: "selge" },
  { inf: "setje",  cls: "j", f: ["set", "sette", "sett"], bm: "sette" },
  { inf: "velje",  cls: "j", f: ["vel", "valde", "valt"], bm: "velge" },
  { inf: "krevje", cls: "j", f: ["krev", "kravde", "kravt"], bm: "kreve" },
  { inf: "byggje|bygge", cls: "j", f: ["byggjer|bygger", "bygde", "bygd"] },
  { inf: "følgje|fylgje", cls: "j", f: ["følgjer|fylgjer", "følgde|fylgde", "følgt|fylgt"], bm: "følge" },
  { inf: "ringje|ringe", cls: "j", f: ["ringjer|ringer", "ringde", "ringt"] },
  // kortverb (-r, -dde, -dd)
  { inf: "bu",     cls: "kort", f: ["bur", "budde", "budd"], bm: "bo" },
  { inf: "nå",     cls: "kort", f: ["når", "nådde", "nådd"] },
  { inf: "tru",    cls: "kort", f: ["trur", "trudde", "trudd"], bm: "tro" },
  { inf: "ha",     cls: "kort", f: ["har", "hadde", "hatt"] },
  { inf: "sy",     cls: "kort", f: ["syr", "sydde", "sydd"] },
  { inf: "snu",    cls: "kort", f: ["snur", "snudde", "snudd"] },
  { inf: "skje",   cls: "kort", f: ["skjer", "skjedde", "skjedd"] },
  // sterke verb (vokalskifte, inga ending i presens og preteritum)
  { inf: "skrive", cls: "sterk", f: ["skriv", "skreiv", "skrive"] },
  { inf: "finne",  cls: "sterk", f: ["finn", "fann", "funne"] },
  { inf: "gå",     cls: "sterk", f: ["går", "gjekk", "gått"] },
  { inf: "vere",   cls: "sterk", f: ["er", "var", "vore"], bm: "være" },
  { inf: "sjå",    cls: "sterk", f: ["ser", "såg", "sett"], bm: "se" },
  { inf: "gi|gje", cls: "sterk", f: ["gir|gjev", "gav|ga", "gitt|gjeve"] },
  { inf: "komme|kome", cls: "sterk", f: ["kjem", "kom", "kome|komme"] },
  { inf: "ete",    cls: "sterk", f: ["et", "åt", "ete"], bm: "spise" },
  { inf: "drikke", cls: "sterk", f: ["drikk", "drakk", "drukke"] },
  { inf: "synge|syngje", cls: "sterk", f: ["syng", "song", "sunge"] },
  { inf: "springe", cls: "sterk", f: ["spring", "sprang", "sprunge"], bm: "løpe" },
  { inf: "bite",   cls: "sterk", f: ["bit", "beit", "bite"] },
  { inf: "fryse",  cls: "sterk", f: ["frys", "fraus", "frose"] },
  { inf: "lese",   cls: "sterk", f: ["les", "las", "lese"] },
  { inf: "sitje",  cls: "sterk", f: ["sit", "sat", "sete"], bm: "sitte" },
  { inf: "liggje", cls: "sterk", f: ["ligg", "låg", "lege"], bm: "ligge" },
  { inf: "ta",     cls: "sterk", f: ["tek|tar", "tok", "teke|tatt"] },
  { inf: "sove",   cls: "sterk", f: ["søv", "sov", "sove"] },
  { inf: "bere",   cls: "sterk", f: ["ber", "bar", "bore"], bm: "bære" },
  { inf: "få",     cls: "sterk", f: ["får", "fekk", "fått"] },
  { inf: "stå",    cls: "sterk", f: ["står", "stod|sto", "stått"] },
  { inf: "slå",    cls: "sterk", f: ["slår", "slo", "slege|slått"] },
  { inf: "dra",    cls: "sterk", f: ["dreg|drar", "drog", "drege|dratt"] },
  { inf: "be",     cls: "sterk", f: ["bed|ber", "bad", "bede|bedt"] },
  { inf: "bryte",  cls: "sterk", f: ["bryt", "braut", "brote"] },
  { inf: "drive",  cls: "sterk", f: ["driv", "dreiv", "drive"] },
  { inf: "flyge|fly", cls: "sterk", f: ["flyg|flyr", "flaug", "floge"] },
  { inf: "gripe",  cls: "sterk", f: ["grip", "greip", "gripe"] },
  { inf: "halde",  cls: "sterk", f: ["held", "heldt", "halde"], bm: "holde" },
  { inf: "nyte",   cls: "sterk", f: ["nyt", "naut", "note"] },
  { inf: "skyte",  cls: "sterk", f: ["skyt", "skaut", "skote"] },
  { inf: "sleppe", cls: "sterk", f: ["slepp", "slapp", "sloppe"], bm: "slippe" },
  { inf: "smelle", cls: "sterk", f: ["smell", "small", "smolle"] },
  { inf: "stele",  cls: "sterk", f: ["stel", "stal", "stole"], bm: "stjele" },
  { inf: "stige",  cls: "sterk", f: ["stig", "steig", "stige"] },
  { inf: "svelte", cls: "sterk", f: ["svelt", "svalt", "svolte"], bm: "sulte" },
  { inf: "vinne",  cls: "sterk", f: ["vinn", "vann", "vunne"] },
  { inf: "bli|verte", cls: "sterk", f: ["blir|vert", "blei|vart", "blitt|vorte"] },
  { inf: "falle",  cls: "sterk", f: ["fell", "fall", "falle"] },
  // uregelrette verb
  { inf: "seie",   cls: "u", f: ["seier", "sa", "sagt"], bm: "si" },
  { inf: "gjere",  cls: "u", f: ["gjer", "gjorde", "gjort"], bm: "gjøre" },
  { inf: "vite",   cls: "u", f: ["veit", "visste", "visst"] },
  { inf: "leggje", cls: "u", f: ["legg", "la|lagde", "lagt"], bm: "legge" },
  { inf: "kunne",  cls: "u", f: ["kan", "kunne", "kunna"] },
  { inf: "ville",  cls: "u", f: ["vil", "ville", "villa"] },
  { inf: "måtte",  cls: "u", f: ["må", "måtte", "måtta"] },
];

/* ---------------- ADJEKTIV ---------------- */
Bank.adjectives = [
  { w: "fin",    f: { n: "fint", pl: "fine", komp: "finare", sup: "finast" } },
  { w: "stor",   f: { n: "stort", pl: "store", komp: "større", sup: "størst" } },
  { w: "god",    f: { n: "godt", pl: "gode", komp: "betre", sup: "best" } },
  { w: "liten",  f: { n: "lite", pl: "små", komp: "mindre", sup: "minst" } },
  { w: "gammal", f: { n: "gammalt", pl: "gamle", komp: "eldre", sup: "eldst" }, bm: "gammel" },
  { w: "ung",    f: { n: "ungt", pl: "unge", komp: "yngre", sup: "yngst" } },
  { w: "lang",   f: { n: "langt", pl: "lange", komp: "lengre", sup: "lengst" } },
  { w: "høg",    f: { n: "høgt", pl: "høge", komp: "høgare", sup: "høgast" }, bm: "høy" },
  { w: "ny",     f: { n: "nytt", pl: "nye", komp: "nyare", sup: "nyast" } },
  { w: "rask",   f: { n: "raskt", pl: "raske", komp: "raskare", sup: "raskast" } },
  { w: "billeg", f: { n: "billeg", pl: "billege", komp: "billegare", sup: "billegast" }, bm: "billig" },
  { w: "vanleg", f: { n: "vanleg", pl: "vanlege", komp: "vanlegare", sup: "vanlegast" }, bm: "vanlig" },
  { w: "varm",   f: { n: "varmt", pl: "varme", komp: "varmare", sup: "varmast" } },
  { w: "kald",   f: { n: "kaldt", pl: "kalde", komp: "kaldare", sup: "kaldast" } },
  { w: "raud",   f: { n: "raudt", pl: "raude", komp: "raudare", sup: "raudast" }, bm: "rød" },
  { w: "grøn",   f: { n: "grønt", pl: "grøne", komp: "grønare", sup: "grønast" }, bm: "grønn" },
  { w: "brei",   f: { n: "breitt", pl: "breie", komp: "breiare", sup: "breiast" }, bm: "bred" },
  { w: "stygg",  f: { n: "stygt", pl: "stygge", komp: "styggare", sup: "styggast" } },
  { w: "snill",  f: { n: "snilt", pl: "snille", komp: "snillare", sup: "snillast" } },
  { w: "tung",   f: { n: "tungt", pl: "tunge", komp: "tyngre", sup: "tyngst" } },
  { w: "lett",   f: { n: "lett", pl: "lette", komp: "lettare", sup: "lettast" } },
  { w: "sterk",  f: { n: "sterkt", pl: "sterke", komp: "sterkare", sup: "sterkast" } },
  { w: "mjuk",   f: { n: "mjukt", pl: "mjuke", komp: "mjukare", sup: "mjukast" }, bm: "myk" },
  { w: "trøytt", f: { n: "trøytt", pl: "trøytte", komp: "trøyttare", sup: "trøyttast" }, bm: "trøtt" },
  { w: "sein",   f: { n: "seint", pl: "seine", komp: "seinare", sup: "seinast" }, bm: "sen" },
  { w: "tidleg", f: { n: "tidleg", pl: "tidlege", komp: "tidlegare", sup: "tidlegast" }, bm: "tidlig" },
  { w: "djup",   f: { n: "djupt", pl: "djupe", komp: "djupare", sup: "djupast" }, bm: "dyp" },
  { w: "låg",    f: { n: "lågt", pl: "låge", komp: "lågare", sup: "lågast" }, bm: "lav" },
  { w: "mørk",   f: { n: "mørkt", pl: "mørke", komp: "mørkare", sup: "mørkast" } },
  { w: "dyr",    f: { n: "dyrt", pl: "dyre", komp: "dyrare", sup: "dyrast" } },
  { w: "rik",    f: { n: "rikt", pl: "rike", komp: "rikare", sup: "rikast" } },
  { w: "fattig", f: { n: "fattig", pl: "fattige", komp: "fattigare", sup: "fattigast" } },
  { w: "heil",   f: { n: "heilt", pl: "heile", komp: "heilare", sup: "heilast" }, bm: "hel" },
  { w: "open",   f: { n: "ope", pl: "opne", komp: "opnare", sup: "opnast" }, bm: "åpen" },
  // fleire: -leg/-ig (utan -t i inkjekjønn), -en (open – ope – opne), -er (vakker – vakkert – vakre)
  { w: "glad",   f: { n: "glad", pl: "glade", komp: "gladare", sup: "gladast" } },
  { w: "redd",   f: { n: "redd", pl: "redde", komp: "reddare", sup: "reddast" } },
  { w: "frisk",  f: { n: "friskt", pl: "friske", komp: "friskare", sup: "friskast" } },
  { w: "sjuk",   f: { n: "sjukt", pl: "sjuke", komp: "sjukare", sup: "sjukast" }, bm: "syk" },
  { w: "rein",   f: { n: "reint", pl: "reine", komp: "reinare", sup: "reinast" }, bm: "ren" },
  { w: "kvit",   f: { n: "kvitt", pl: "kvite", komp: "kvitare", sup: "kvitast" }, bm: "hvit" },
  { w: "tjukk",  f: { n: "tjukt", pl: "tjukke", komp: "tjukkare", sup: "tjukkast" }, bm: "tykk" },
  { w: "vakker", f: { n: "vakkert", pl: "vakre", komp: "vakrare", sup: "vakrast" } },
  { w: "sikker", f: { n: "sikkert", pl: "sikre", komp: "sikrare", sup: "sikrast" } },
  { w: "vaken",  f: { n: "vake", pl: "vakne", komp: "vaknare", sup: "vaknast" }, bm: "våken" },
  { w: "moden",  f: { n: "mode", pl: "modne", komp: "modnare", sup: "modnast" } },
  { w: "viktig", f: { n: "viktig", pl: "viktige", komp: "viktigare", sup: "viktigast" } },
  { w: "lykkeleg", f: { n: "lykkeleg", pl: "lykkelege", komp: "lykkelegare", sup: "lykkelegast" }, bm: "lykkelig" },
  { w: "farleg", f: { n: "farleg", pl: "farlege", komp: "farlegare", sup: "farlegast" }, bm: "farlig" },
  { w: "kjedeleg", f: { n: "kjedeleg", pl: "kjedelege", komp: "kjedelegare", sup: "kjedelegast" }, bm: "kjedelig" },
  { w: "venleg", f: { n: "venleg", pl: "venlege", komp: "venlegare", sup: "venlegast" }, bm: "vennlig" },
  { w: "ærleg",  f: { n: "ærleg", pl: "ærlege", komp: "ærlegare", sup: "ærlegast" }, bm: "ærlig" },
  { w: "roleg",  f: { n: "roleg", pl: "rolege", komp: "rolegare", sup: "rolegast" }, bm: "rolig" },
  { w: "morosam", f: { n: "morosamt", pl: "morosame", komp: "morosamare", sup: "morosamast" }, bm: "morsom" },
  { w: "dårleg", f: { n: "dårleg", pl: "dårlege", komp: "dårlegare|verre", sup: "dårlegast|verst" }, bm: "dårlig" },
];

/* ---------------- SMÅORD (bokmål → nynorsk) ----------------
   Berre ord som faktisk er ulike på nynorsk. Ord som er tillatne i same form
   (nå, igjen, også, vi, derfor, mens, blant …) står ikkje her.
   NB: drills.js lagar nøkkel av bm, så same bm kan ikkje stå to gonger. Bruk | og cue i staden. */
Bank.words = [
  // Spørjeord
  { bm: "hva",       nn: "kva",    wrong: ["ka", "kvad"], tags: ["sporjeord"] },
  { bm: "hvem",      nn: "kven",   wrong: ["kvem", "kem"], tags: ["sporjeord"] },
  { bm: "hvor",      nn: "kvar|kor", cue: "(kvar = stad, kor = grad/mengd)", wrong: ["kvor", "hvor"], tags: ["sporjeord"], why: "<em class=\"nn\">kvar</em> spør om stad («Kvar bur du?»), <em class=\"nn\">kor</em> spør om grad eller mengd («Kor gammal er du?»)." },
  { bm: "hvordan",   nn: "korleis", wrong: ["kordan", "kvordan"], tags: ["sporjeord"] },
  { bm: "hvorfor",   nn: "kvifor", wrong: ["kvorfor", "korfor"], tags: ["sporjeord"] },
  { bm: "hvilken",   nn: "kva for ein|kva for", cue: "(hvilken bil?)", wrong: ["kvilken", "kven"], tags: ["sporjeord"] },
  { bm: "hvilket",   nn: "kva for eit|kva for", cue: "(hvilket hus?)", wrong: ["kvilket", "kva for ein"], tags: ["sporjeord"] },
  { bm: "hvilke",    nn: "kva for nokre|kva for", cue: "(hvilke bøker?)", wrong: ["kvilke", "kva for ein"], tags: ["sporjeord"] },
  { bm: "hva slags", nn: "kva slags", wrong: ["kva for slags", "ka slags"], tags: ["sporjeord"] },
  { bm: "hvor mange", nn: "kor mange", wrong: ["kvar mange", "kor mangen"], tags: ["sporjeord"] },
  { bm: "hvor mye",  nn: "kor mykje", wrong: ["kvar mykje", "kor mye"], tags: ["sporjeord"] },
  { bm: "hvor lenge", nn: "kor lenge", wrong: ["kvar lenge", "kor lengje"], tags: ["sporjeord"] },
  { bm: "hvor langt", nn: "kor langt", wrong: ["kvar langt", "kor lang"], tags: ["sporjeord"] },

  // Pronomen
  { bm: "jeg",       nn: "eg",     wrong: ["e", "jeg"], tags: ["pronomen"] },
  { bm: "hun",       nn: "ho",     wrong: ["hun", "hu"], tags: ["pronomen"] },
  { bm: "dem",       nn: "dei",    wrong: ["dem", "de"], tags: ["pronomen"] },
  { bm: "de",        nn: "dei",    cue: "(de kommer i morgen)", wrong: ["de", "dem"], tags: ["pronomen"], why: "Bokmål <em class=\"bm\">de</em> (3. person fleirtal) heiter <em class=\"nn\">dei</em>. Pass på: <em class=\"nn\">de</em> på nynorsk tyder «dere»." },
  { bm: "dere",      nn: "de|dykk|dokker", cue: "(de = subjekt, dykk = objekt)", wrong: ["dere", "dei"], tags: ["pronomen"], why: "<em class=\"bm\">dere</em> heiter <em class=\"nn\">de</em> som subjekt («De kjem») og <em class=\"nn\">dykk</em> som objekt («Eg ser dykk»). <em class=\"nn\">Dokker</em> er tillate i begge funksjonane." },
  { bm: "deres",     nn: "deira|dykkar", cue: "(deira = til dei, dykkar = til dykk)", wrong: ["deres", "deiras"], tags: ["pronomen"], why: "<em class=\"nn\">deira</em> = det som høyrer til <em class=\"nn\">dei</em>; <em class=\"nn\">dykkar</em> = det som høyrer til <em class=\"nn\">de/dykk</em>." },
  { bm: "hennes",    nn: "hennar", wrong: ["hennes", "hennas"], tags: ["pronomen"] },
  { bm: "hverandre", nn: "kvarandre", wrong: ["kverandre", "hverandre"], tags: ["pronomen"] },
  { bm: "ham",       nn: "han|honom", cue: "(som objekt: jeg så ham)", wrong: ["ham", "hann"], tags: ["pronomen"] },
  { bm: "noen",      nn: "nokon|nokre|noka", cue: "(nokon = eintal, nokre = fleirtal)", wrong: ["noen", "noko"], tags: ["pronomen"], why: "<em class=\"bm\">noen</em> heiter <em class=\"nn\">nokon</em> i eintal (hankjønn), <em class=\"nn\">noka</em> (hokjønn) og <em class=\"nn\">nokre</em> i fleirtal. <em class=\"nn\">noko</em> = «noe»." },
  { bm: "disse",     nn: "desse",  wrong: ["disse", "dese"], tags: ["pronomen"] },
  { bm: "man",       nn: "ein",    cue: "(man kan aldri vite)", wrong: ["man", "mann"], tags: ["pronomen"], why: "Det ubestemte <em class=\"bm\">man</em> heiter <em class=\"nn\">ein</em> på nynorsk: «Ein kan aldri vite»." },
  { bm: "annen",     nn: "annan",  cue: "(en annen dag)", wrong: ["annen", "anna"], tags: ["pronomen"] },
  { bm: "annet",     nn: "anna",   cue: "(et annet hus)", wrong: ["annet", "annan"], tags: ["pronomen"] },
  { bm: "selv",      nn: "sjølv",  cue: "(jeg gjorde det selv)", wrong: ["sjøl", "selv"], tags: ["pronomen"] },

  // Småord: adverb, konjunksjonar, preposisjonar
  { bm: "ikke",      nn: "ikkje",  wrong: ["ikje", "ike"], tags: ["smaord"] },
  { bm: "bare",      nn: "berre",  wrong: ["bere", "barre"], tags: ["smaord"] },
  { bm: "kun",       nn: "berre",  wrong: ["kun", "kunn"], tags: ["smaord"], why: "<em class=\"bm\">kun</em> finst ikkje på nynorsk – skriv <em class=\"nn\">berre</em>." },
  { bm: "fra",       nn: "frå",    wrong: ["fra", "fraa"], tags: ["smaord"] },
  { bm: "mye",       nn: "mykje",  wrong: ["mye", "myke"], tags: ["smaord"] },
  { bm: "noe",       nn: "noko",   wrong: ["nokon", "noe"], tags: ["smaord"] },
  { bm: "sammen",    nn: "saman",  wrong: ["sammen", "samen"], tags: ["smaord"] },
  { bm: "hvis",      nn: "viss|dersom|om", wrong: ["kvis", "hvis"], tags: ["smaord"] },
  { bm: "annerledes", nn: "annleis", wrong: ["annerleis", "anleis"], tags: ["smaord"] },
  { bm: "da",        nn: "då",     wrong: ["da", "so"], tags: ["smaord"] },
  { bm: "siden",     nn: "sidan",  wrong: ["siden", "sida"], tags: ["smaord"] },
  { bm: "ennå",      nn: "enno|endå", wrong: ["ennå", "ennu"], tags: ["smaord"] },
  { bm: "enda",      nn: "endå",   cue: "(enda bedre)", wrong: ["enda", "enno"], tags: ["smaord"], why: "Om grad («endå betre», «endå ein») heiter det <em class=\"nn\">endå</em>. <em class=\"nn\">enno</em> tyder «framleis»." },
  { bm: "mer",       nn: "meir",   wrong: ["mer", "mere"], tags: ["smaord"] },
  { bm: "flere",     nn: "fleire", wrong: ["flere", "fleir"], tags: ["smaord"] },
  { bm: "hjemme",    nn: "heime",  wrong: ["hjemme", "heima"], tags: ["smaord"] },
  { bm: "hjem",      nn: "heim",   cue: "(jeg går hjem)", wrong: ["hjem", "heime"], tags: ["smaord"] },
  { bm: "hver",      nn: "kvar",   cue: "(hver dag)", wrong: ["kver", "hver"], tags: ["smaord"] },
  { bm: "hvert",     nn: "kvart",  cue: "(hvert år)", wrong: ["kvert", "hvert"], tags: ["smaord"] },
  { bm: "uten",      nn: "utan",   wrong: ["uten", "utann"], tags: ["smaord"] },
  { bm: "utenfor",   nn: "utanfor", wrong: ["utenfor", "utafor"], tags: ["smaord"] },
  { bm: "innenfor",  nn: "innanfor", wrong: ["innenfor", "innafor"], tags: ["smaord"] },
  { bm: "dessverre", nn: "diverre|dessverre", wrong: ["desverre"], tags: ["smaord"] },
  { bm: "dessuten",  nn: "dessutan", wrong: ["dessuten", "dessutann"], tags: ["smaord"] },
  { bm: "allerede",  nn: "alt|allereie", wrong: ["allerede", "alereie"], tags: ["smaord"] },
  { bm: "enten",     nn: "anten",  cue: "(enten … eller)", wrong: ["enten", "antan"], tags: ["smaord"] },
  { bm: "selv om",   nn: "sjølv om|endå om", wrong: ["sjøl om", "selv om"], tags: ["smaord"] },
  { bm: "nemlig",    nn: "nemleg", wrong: ["nemlig", "nemligt"], tags: ["smaord"] },
  { bm: "egentlig",  nn: "eigentleg", wrong: ["egentlig", "eigenleg"], tags: ["smaord"] },
  { bm: "virkelig",  nn: "verkeleg", wrong: ["virkelig", "virkeleg"], tags: ["smaord"] },
  { bm: "endelig",   nn: "endeleg", wrong: ["endelig", "endelegt"], tags: ["smaord"] },
  { bm: "sjelden",   nn: "sjeldan", wrong: ["sjelden", "sjeldent"], tags: ["smaord"] },
  { bm: "plutselig", nn: "plutseleg|brått", wrong: ["plutselig", "plutsleg"], tags: ["smaord"] },
  { bm: "særlig",    nn: "særleg", wrong: ["særlig", "særlegt"], tags: ["smaord"] },
  { bm: "alene",     nn: "aleine|åleine", wrong: ["alene", "alleine"], tags: ["smaord"] },
  { bm: "senere",    nn: "seinare", wrong: ["senere", "seinere"], tags: ["smaord"] },
  { bm: "tidligere", nn: "tidlegare", wrong: ["tidligere", "tidlegere"], tags: ["smaord"] },
  { bm: "istedenfor", nn: "i staden for", wrong: ["istedenfor", "i stedet for"], tags: ["smaord"] },
  { bm: "foran",     nn: "framfor|føre", cue: "(foran huset)", wrong: ["foran", "forann"], tags: ["smaord"] },
  { bm: "for eksempel", nn: "til dømes|for eksempel", wrong: ["til dømmes", "for eksempell"], tags: ["smaord"] },
  { bm: "hele",      nn: "heile",  cue: "(hele dagen)", wrong: ["hele", "heila"], tags: ["smaord"] },
  { bm: "bortsett fra", nn: "bortsett frå", wrong: ["bortsett fra", "bortsedd frå"], tags: ["smaord"] },
  { bm: "ifølge",    nn: "ifølgje", wrong: ["ifølge", "ifylge"], tags: ["smaord"] },
  { bm: "forrige",   nn: "førre",  cue: "(forrige uke)", wrong: ["forrige", "førrige"], tags: ["smaord"] },

  // an-/be-/-het/-else-ord
  { bm: "kjærlighet", nn: "kjærleik", wrong: ["kjærlegheit", "kjærlighet"], tags: ["het"] },
  { bm: "mulighet",  nn: "moglegheit|høve|sjanse", wrong: ["mulegheit", "mulighet"], tags: ["het"] },
  { bm: "sannhet",   nn: "sanning", wrong: ["sannheit", "sannhet"], tags: ["het"] },
  { bm: "frihet",    nn: "fridom",  wrong: ["friheit", "frihet"], tags: ["het"] },
  { bm: "sikkerhet", nn: "tryggleik|sikkerheit", wrong: ["sikkerhet", "trygghet"], tags: ["het"] },
  { bm: "hemmelighet", nn: "løyndom|hemmelegheit", wrong: ["hemmelighet", "løynddom"], tags: ["het"] },
  { bm: "virkelighet", nn: "røynd|verkelegheit", wrong: ["virkelighet", "verkeligheit"], tags: ["het"] },
  { bm: "nyhet",     nn: "nyheit|nyhende", wrong: ["nyhet", "nyhet"], tags: ["het"] },
  { bm: "begynnelse", nn: "byrjing|start|begynning", wrong: ["begynnelse", "byrjelse"], tags: ["het"] },
  { bm: "hendelse",  nn: "hending", wrong: ["hendelse", "hendelsen"], tags: ["het"] },
  { bm: "følelse",   nn: "kjensle", wrong: ["følelse", "fylelse"], tags: ["het"] },
  { bm: "avgjørelse", nn: "avgjerd|avgjersle", wrong: ["avgjørelse", "avgjerelse"], tags: ["het"] },
  { bm: "opplevelse", nn: "oppleving", wrong: ["opplevelse", "opplevning"], tags: ["het"] },
  { bm: "overraskelse", nn: "overrasking", wrong: ["overraskelse", "overraskning"], tags: ["het"] },
  { bm: "øvelse",    nn: "øving",   wrong: ["øvelse", "øvning"], tags: ["het"] },
  { bm: "løsning",   nn: "løysing", wrong: ["løsning", "løysning"], tags: ["het"] },
  { bm: "mening",    nn: "meining", cue: "(hva er meningen?)", wrong: ["mening", "meaning"], tags: ["het"] },
  { bm: "betydning", nn: "tyding|betydning", wrong: ["betyding", "tydning"], tags: ["het"] },
  { bm: "innhold",   nn: "innhald", wrong: ["innhold", "inhald"], tags: ["het"] },
  { bm: "utdannelse", nn: "utdanning", wrong: ["utdannelse", "utdaning"], tags: ["het"] },

  // Adjektiv og adverb
  { bm: "vanskelig", nn: "vanskeleg", wrong: ["vanskelig", "vanskelegt"], tags: ["adjektiv"] },
  { bm: "tidlig",    nn: "tidleg",  wrong: ["tidlig", "tidlegt"], tags: ["adjektiv"] },
  { bm: "sent",      nn: "seint",   cue: "(for sent)", wrong: ["sent", "seinnt"], tags: ["adjektiv"] },
  { bm: "morsom",    nn: "morosam", wrong: ["morsom", "morsam"], tags: ["adjektiv"] },
  { bm: "mulig",     nn: "mogleg",  wrong: ["mulig", "muleg"], tags: ["adjektiv"] },
  { bm: "umulig",    nn: "umogleg", wrong: ["umulig", "umuleg"], tags: ["adjektiv"] },
  { bm: "hyggelig",  nn: "hyggeleg|koseleg", wrong: ["hyggelig", "hyggleg"], tags: ["adjektiv"] },
  { bm: "sulten",    nn: "svolten|sulten", wrong: ["svulten", "sultent"], tags: ["adjektiv"] },
  { bm: "rød",       nn: "raud",    wrong: ["rød", "røyd"], tags: ["adjektiv"] },
  { bm: "høy",       nn: "høg",     wrong: ["høy", "høgg"], tags: ["adjektiv"] },
  { bm: "gammel",    nn: "gammal",  wrong: ["gammel", "gamal"], tags: ["adjektiv"] },
  { bm: "syk",       nn: "sjuk",    wrong: ["syk", "sjyk"], tags: ["adjektiv"] },
  { bm: "spennende", nn: "spennande", wrong: ["spennende", "spenande"], tags: ["adjektiv"] },
  { bm: "levende",   nn: "levande", wrong: ["levende", "levanne"], tags: ["adjektiv"] },
  { bm: "eneste",    nn: "einaste", wrong: ["eneste", "eineste"], tags: ["adjektiv"] },

  // Diverse
  { bm: "sykdom",    nn: "sjukdom", wrong: ["sykdom", "sjukdomm"], tags: ["diverse"] },
  { bm: "penger",    nn: "pengar",  wrong: ["penger", "pengane"], tags: ["diverse"] },
  { bm: "klær",      nn: "klede",   wrong: ["klær", "kleder"], tags: ["diverse"] },
  { bm: "melk",      nn: "mjølk",   wrong: ["melk", "mjelk"], tags: ["diverse"] },
  { bm: "kaffe",     nn: "kaffi|kaffe", wrong: ["kaffie"], tags: ["diverse"] },
  { bm: "morgen",    nn: "morgon",  wrong: ["morgen", "morgan"], tags: ["diverse"] },
  { bm: "måned",     nn: "månad",   wrong: ["måned", "månd"], tags: ["diverse"] },
  { bm: "mandag",    nn: "måndag",  wrong: ["mandag", "manndag"], tags: ["diverse"] },
  { bm: "tirsdag",   nn: "tysdag",  wrong: ["tirsdag", "tyrsdag"], tags: ["diverse"] },
  { bm: "lørdag",    nn: "laurdag", wrong: ["lørdag", "lauredag"], tags: ["diverse"] },
  { bm: "høst",      nn: "haust",   wrong: ["høst", "hauste"], tags: ["diverse"] },
  { bm: "oppgave",   nn: "oppgåve", wrong: ["oppgave", "opgåve"], tags: ["diverse"] },
  { bm: "stue",      nn: "stove",   wrong: ["stue", "stova"], tags: ["diverse"] },
  { bm: "gulv",      nn: "golv",    wrong: ["gulv", "gålv"], tags: ["diverse"] },
  { bm: "verden",    nn: "verda",   wrong: ["verden", "verdet"], tags: ["diverse"] },
  { bm: "hode",      nn: "hovud",   wrong: ["hode", "hovod"], tags: ["diverse"] },
  { bm: "øre",       nn: "øyre",    wrong: ["øre", "øyra"], tags: ["diverse"] },
  { bm: "mennesker", nn: "menneske", wrong: ["mennesker", "menneskar"], tags: ["diverse"] },
];

/* ---------------- SETNINGAR (handskrivne) ----------------
   Kvart element må ha minst to gale options, slik at fleirvalsvarianten får tre val. */
Bank.sentences = {
  pronomen: [
    { prompt: "Eg såg ___ i går.", cue: "(ho / henne)", accept: ["henne"], options: ["ho", "hun"], why: "<em class=\"nn\">henne</em> er objektsform: eg såg <em class=\"nn\">henne</em>." },
    { prompt: "___ kjem i morgon.", cue: "(ho / henne)", accept: ["Ho"], options: ["Henne", "Hun"], why: "<em class=\"nn\">ho</em> er subjektsform: <em class=\"nn\">ho</em> kjem." },
    { prompt: "Vi såg ___ på kino.", cue: "(dei / dykk)", accept: ["dei"], options: ["dykk", "dem"], why: "<em class=\"nn\">dei</em> er både subjekts- og objektsform i 3. person fleirtal. <em class=\"bm\">dem</em> finst ikkje på nynorsk." },
    { prompt: "Kan ___ hjelpe meg?", cue: "(de / dykk)", accept: ["de", "dokker"], options: ["dykk", "dere"], why: "<em class=\"nn\">de</em> er subjektsform i 2. person fleirtal («Kan de hjelpe meg?»). <em class=\"nn\">dykk</em> er objektsform." },
    { prompt: "Eg skal ringje ___ i kveld.", cue: "(de / dykk)", accept: ["dykk", "dokker"], options: ["de", "dere"], why: "<em class=\"nn\">dykk</em> er objektsform: eg ringjer <em class=\"nn\">dykk</em>." },
    { prompt: "___ er trøytte etter turen.", cue: "(dei / de)", accept: ["Dei"], options: ["De", "Dem"], why: "<em class=\"nn\">dei</em> = «de/dem» på bokmål. <em class=\"nn\">de</em> på nynorsk tyder «dere»." },
    { prompt: "Har du snakka med ___?", cue: "(han / honom)", accept: ["han", "honom"], options: ["ham", "hann"], why: "På nynorsk er <em class=\"nn\">han</em> både subjekts- og objektsform. <em class=\"nn\">honom</em> er òg lov som objekt. <em class=\"bm\">ham</em> er bokmål." },
    { prompt: "Læraren gav ___ ei ny bok.", cue: "(eg / meg)", accept: ["meg"], options: ["eg", "jeg"], why: "<em class=\"nn\">meg</em> er objektsform: læraren gav <em class=\"nn\">meg</em> boka." },
    { prompt: "___ er den beste venen min.", cue: "(han / honom)", accept: ["Han"], options: ["Honom", "Ham"], why: "Subjektet i setninga må stå i subjektsform: <em class=\"nn\">han</em>." },
    { prompt: "Ho fortalde ___ alt.", cue: "(vi / oss)", accept: ["oss"], options: ["vi", "me"], why: "<em class=\"nn\">oss</em> er objektsform: ho fortalde <em class=\"nn\">oss</em> alt." },
    { prompt: "___ skal på tur i helga.", cue: "(vi / oss)", accept: ["Vi", "Me"], options: ["Oss", "Dokker"], why: "Både <em class=\"nn\">vi</em> og <em class=\"nn\">me</em> er tillatne som subjekt. <em class=\"nn\">oss</em> er objektsform." },
    { prompt: "Har ___ sett filmen?", cue: "(de / dykk)", accept: ["de", "dokker"], options: ["dykk", "dere"], why: "Subjekt i 2. person fleirtal: <em class=\"nn\">de</em> (eller <em class=\"nn\">dokker</em>)." },
    { prompt: "Jenta var sjuk, så eg ringde ___.", cue: "(ho / henne)", accept: ["henne"], options: ["ho", "hu"], why: "Objektsform av <em class=\"nn\">ho</em> er <em class=\"nn\">henne</em>." },
    { prompt: "Eg skal gje ___ ein sjanse til.", cue: "(han / ham)", accept: ["han", "honom"], options: ["ham", "hans"], why: "<em class=\"nn\">han</em> er òg objektsform på nynorsk. <em class=\"bm\">ham</em> finst ikkje." },
    { prompt: "Kjenner du ___ som bur i det raude huset?", cue: "(dei / dykk)", accept: ["dei"], options: ["dykk", "dem"], why: "3. person fleirtal heiter <em class=\"nn\">dei</em> både som subjekt og objekt." },
  ],
  nokon: [
    { prompt: "Er det ___ heime?", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">nokon</em> brukar vi om personar og hankjønnsord i eintal." },
    { prompt: "Vil du ha ___ kaffi?", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "<em class=\"nn\">noko</em> brukar vi om mengd («noko kaffi») og om inkjekjønnsord." },
    { prompt: "Eg har lese ___ bøker i sommar.", cue: "(nokon / noko / nokre)", accept: ["nokre"], options: ["nokon", "noko"], why: "<em class=\"nn\">nokre</em> er fleirtalsforma: nokre bøker." },
    { prompt: "Har du ___ å drikke?", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "<em class=\"nn\">noko</em> brukar vi om «noe» – ei ubestemt mengd eller ein ubestemt ting." },
    { prompt: "Han såg ___ hund i hagen.", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">hund</em> er hankjønn: <em class=\"nn\">nokon</em> hund." },
    { prompt: "Det ligg ___ avis på bordet.", cue: "(noka / noko / nokre)", accept: ["noka", "nokon"], options: ["noko", "nokre"], why: "<em class=\"nn\">avis</em> er hokjønn: <em class=\"nn\">noka</em> (eller <em class=\"nn\">nokon</em>) avis." },
    { prompt: "Kan ___ hjelpe meg med leksene?", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "Om ein person: <em class=\"nn\">nokon</em>." },
    { prompt: "Det står ___ elevar utanfor.", cue: "(nokon / noko / nokre)", accept: ["nokre"], options: ["nokon", "noko"], why: "Fleirtal: <em class=\"nn\">nokre</em> elevar." },
    { prompt: "Eg ser ikkje ___ hus her.", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "<em class=\"nn\">hus</em> er inkjekjønn: <em class=\"nn\">noko</em> hus." },
    { prompt: "Vil du ha ___ eple?", cue: "(nokon / noko / nokre)", accept: ["nokre"], options: ["nokon", "noko"], why: "Fleire eple: <em class=\"nn\">nokre</em> eple. (Eitt eple: <em class=\"nn\">eit</em> eple.)" },
    { prompt: "Kjenner du ___ som kan spele gitar?", cue: "(nokon / noko / nokre)", accept: ["nokon"], options: ["noko", "nokre"], why: "Om ein person: <em class=\"nn\">nokon</em>." },
    { prompt: "Er det ___ nytt?", cue: "(nokon / noko / nokre)", accept: ["noko"], options: ["nokon", "nokre"], why: "«Noe nytt» = <em class=\"nn\">noko</em> nytt." },
  ],
  daNar: [
    { prompt: "___ eg var liten, budde vi i Bergen.", cue: "(då / når)", accept: ["Då"], options: ["Når", "Da"], why: "<em class=\"nn\">då</em> om éin gong i fortida: «den gongen då». <em class=\"nn\">når</em> om noko som skjer fleire gonger eller i framtida: «kvar gong når»." },
    { prompt: "___ det regnar, blir eg inne.", cue: "(då / når)", accept: ["Når"], options: ["Då", "Da"], why: "Noko som skjer kvar gong: <em class=\"nn\">når</em>." },
    { prompt: "Ring meg ___ du kjem fram.", cue: "(då / når)", accept: ["når"], options: ["då", "da"], why: "Framtid: <em class=\"nn\">når</em>." },
    { prompt: "Vi jubla ___ laget skåra.", cue: "(då / når)", accept: ["då"], options: ["når", "da"], why: "Éin gong i fortida: <em class=\"nn\">då</em>." },
    { prompt: "___ eg kjem heim, skal eg ete middag.", cue: "(då / når)", accept: ["Når"], options: ["Då", "Da"], why: "Framtid: <em class=\"nn\">når</em>." },
    { prompt: "Eg var berre sju år ___ vi flytta.", cue: "(då / når)", accept: ["då"], options: ["når", "da"], why: "Éin bestemt gong i fortida: <em class=\"nn\">då</em>." },
    { prompt: "Kvar gong ___ det snør, går vi på ski.", cue: "(då / når)", accept: ["når"], options: ["då", "da"], why: "Gjentaking («kvar gong»): <em class=\"nn\">når</em>." },
    { prompt: "___ vi kom fram, var butikken stengd.", cue: "(då / når)", accept: ["Då"], options: ["Når", "Da"], why: "Éin gong i fortida: <em class=\"nn\">då</em>." },
    { prompt: "Kva skal du gjere ___ du er ferdig med skulen?", cue: "(då / når)", accept: ["når"], options: ["då", "da"], why: "Framtid: <em class=\"nn\">når</em>." },
  ],
  kvarKor: [
    { prompt: "___ bur du?", cue: "(kvar / kor)", accept: ["Kvar"], options: ["Kor", "Hvor"], why: "<em class=\"nn\">kvar</em> spør om stad." },
    { prompt: "___ gammal er du?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar", "Hvor"], why: "<em class=\"nn\">kor</em> spør om grad eller mengd." },
    { prompt: "___ mange kjem i kveld?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar", "Hvor"], why: "<em class=\"nn\">kor</em> spør om mengd." },
    { prompt: "Veit du ___ nøklane er?", cue: "(kvar / kor)", accept: ["kvar"], options: ["kor", "hvor"], why: "<em class=\"nn\">kvar</em> spør om stad." },
    { prompt: "___ langt er det til skulen?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar", "Hvor"], why: "Grad («kor langt»): <em class=\"nn\">kor</em>." },
    { prompt: "Ho spurde ___ eg hadde vore.", cue: "(kvar / kor)", accept: ["kvar"], options: ["kor", "hvor"], why: "Stad: <em class=\"nn\">kvar</em>." },
    { prompt: "___ mykje kostar det?", cue: "(kvar / kor)", accept: ["Kor"], options: ["Kvar", "Hvor"], why: "Mengd: <em class=\"nn\">kor</em>." },
    { prompt: "Eg lurer på ___ han skal reise.", cue: "(kvar / kor)", accept: ["kvar"], options: ["kor", "hvor"], why: "Stad: <em class=\"nn\">kvar</em>." },
  ],
  possessiv: [
    { prompt: "Per tok ___ bok og gjekk.", cue: "(si / hans)", accept: ["si"], options: ["hans", "sin"], why: "Boka høyrer til subjektet (Per) – då bruker vi <em class=\"nn\">sin/si/sitt/sine</em>. <em class=\"nn\">bok</em> er hokjønn: <em class=\"nn\">si</em> bok." },
    { prompt: "Kari møtte Ola og ___ bror.", cue: "(sin / hans)", accept: ["hans"], options: ["sin", "sine"], why: "Broren høyrer til Ola, ikkje til subjektet Kari. Då bruker vi <em class=\"nn\">hans</em>." },
    { prompt: "Jentene henta ___ jakker.", cue: "(sine / deira)", accept: ["sine"], options: ["deira", "sin"], why: "Jakkene høyrer til subjektet (jentene): <em class=\"nn\">sine</em> jakker." },
    { prompt: "Ho gløymde ___ nøklar heime.", cue: "(sine / hennar)", accept: ["sine"], options: ["hennar", "sin"], why: "Nøklane høyrer til subjektet (ho): <em class=\"nn\">sine</em>. <em class=\"nn\">hennar</em> ville tyde nøklane til ei anna jente." },
    { prompt: "Eg såg Anne og ___ hund i parken.", cue: "(sin / hennar)", accept: ["hennar"], options: ["sin", "si"], why: "Hunden høyrer til Anne, ikkje til subjektet (eg): <em class=\"nn\">hennar</em>." },
    { prompt: "Guten leikar med ___ nye bil.", cue: "(sin / hans)", accept: ["sin"], options: ["hans", "si"], why: "Bilen høyrer til subjektet (guten), og <em class=\"nn\">bil</em> er hankjønn: <em class=\"nn\">sin</em>." },
    { prompt: "Barnet fann ___ eple under bordet.", cue: "(sitt / hans)", accept: ["sitt"], options: ["hans", "sin"], why: "Eplet høyrer til subjektet, og <em class=\"nn\">eple</em> er inkjekjønn: <em class=\"nn\">sitt</em>." },
    { prompt: "Læraren snakka med elevane og ___ foreldre.", cue: "(sine / deira)", accept: ["deira"], options: ["sine", "hans"], why: "Foreldra høyrer til elevane, ikkje til subjektet (læraren): <em class=\"nn\">deira</em>." },
    { prompt: "Ola og Kari selde huset ___.", cue: "(sitt / deira)", accept: ["sitt"], options: ["deira", "sin"], why: "Huset høyrer til subjektet (Ola og Kari): <em class=\"nn\">sitt</em>. <em class=\"nn\">hus</em> er inkjekjønn." },
    { prompt: "Kari fortalde at mor ___ var sjuk.", cue: "(si / hennar)", accept: ["hennar"], options: ["si", "sin"], why: "«Mor» er subjekt i leddsetninga, og eit subjekt kan ikkje ha <em class=\"nn\">sin/si</em>. Difor: mor <em class=\"nn\">hennar</em>." },
  ],
  ennoEnda: [
    { prompt: "Er du ___ ikkje ferdig?", cue: "(enno / endå)", accept: ["enno", "endå"], options: ["ennå", "enda"], why: "Om tid («framleis») bruker vi <em class=\"nn\">enno</em> (eller <em class=\"nn\">endå</em>). <em class=\"bm\">ennå</em> er bokmål." },
    { prompt: "Dette var ___ betre enn i fjor.", cue: "(enno / endå)", accept: ["endå"], options: ["enno", "ennå"], why: "Om grad («endå betre») kan du berre bruke <em class=\"nn\">endå</em>." },
    { prompt: "Han bur ___ heime hos foreldra.", cue: "(enno / endå)", accept: ["enno", "endå"], options: ["ennå", "enda"], why: "Tid («framleis»): <em class=\"nn\">enno</em> eller <em class=\"nn\">endå</em>." },
    { prompt: "Vil du ha ___ ein kopp kaffi?", cue: "(enno / endå)", accept: ["endå"], options: ["enno", "ennå"], why: "«Endå ein» = «enda en» – her må det vere <em class=\"nn\">endå</em>." },
    { prompt: "Vi har ___ ikkje fått svar.", cue: "(enno / endå)", accept: ["enno", "endå"], options: ["ennå", "enda"], why: "Tid: <em class=\"nn\">enno</em> (eller <em class=\"nn\">endå</em>)." },
    { prompt: "Det blei ___ verre etter pausen.", cue: "(enno / endå)", accept: ["endå"], options: ["enno", "enda"], why: "Grad («endå verre»): <em class=\"nn\">endå</em>." },
    { prompt: "Eg har ___ ikkje lese boka.", cue: "(enno / endå)", accept: ["enno", "endå"], options: ["ennå", "enda"], why: "Tid: <em class=\"nn\">enno</em> (eller <em class=\"nn\">endå</em>)." },
  ],
  ogsaa: [
    { prompt: "Eg vil ___ vere med.", cue: "(òg / og)", accept: ["òg", "også"], options: ["og", "ogso"], why: "Kan du byte ut ordet med «i tillegg»? Då er det adverbet <em class=\"nn\">òg</em>/<em class=\"nn\">også</em>, ikkje konjunksjonen <em class=\"nn\">og</em>." },
    { prompt: "Kari ___ Per kjem i kveld.", cue: "(òg / og)", accept: ["og"], options: ["òg", "også"], why: "Bind saman to ledd: konjunksjonen <em class=\"nn\">og</em>." },
    { prompt: "Han er flink i matte, og ___ i norsk.", cue: "(òg / og)", accept: ["òg", "også"], options: ["og", "ogso"], why: "«I tillegg i norsk»: <em class=\"nn\">òg</em>/<em class=\"nn\">også</em>." },
    { prompt: "Vi ___ dei andre gjekk heim.", cue: "(òg / og)", accept: ["og"], options: ["òg", "også"], why: "Bind saman «vi» og «dei andre»: <em class=\"nn\">og</em>." },
    { prompt: "Kjem du ___?", cue: "(òg / og)", accept: ["òg", "også"], options: ["og", "ogso"], why: "«Kjem du i tillegg?»: <em class=\"nn\">òg</em>/<em class=\"nn\">også</em>." },
    { prompt: "Ho syng ___ dansar.", cue: "(òg / og)", accept: ["og"], options: ["òg", "også"], why: "Bind saman to verb: <em class=\"nn\">og</em>." },
    { prompt: "Det var kaldt, og det regna ___.", cue: "(òg / og)", accept: ["òg", "også"], options: ["og", "ogso"], why: "«Det regna i tillegg»: <em class=\"nn\">òg</em>/<em class=\"nn\">også</em>. Hugs aksenten på <em class=\"nn\">òg</em>." },
  ],
  refleksiv: [
    { prompt: "Han vaska ___ før middag.", cue: "(seg / han)", accept: ["seg"], options: ["han", "sjølv"], why: "Når objektet er den same som subjektet, bruker vi det refleksive <em class=\"nn\">seg</em>." },
    { prompt: "Ho såg på ___ i spegelen.", cue: "(seg / henne)", accept: ["seg", "seg sjølv"], options: ["henne", "ho"], why: "Same person som subjektet: <em class=\"nn\">seg</em>. <em class=\"nn\">henne</em> ville tyde ei anna jente." },
    { prompt: "Dei hjelpte ___ med leksene.", cue: "(seg / kvarandre)", accept: ["kvarandre"], options: ["seg", "hverandre"], why: "Gjensidig handling («den eine hjelpte den andre»): <em class=\"nn\">kvarandre</em>." },
    { prompt: "Guten skada ___ på isen.", cue: "(seg / han)", accept: ["seg"], options: ["han", "honom"], why: "Refleksivt: guten skada <em class=\"nn\">seg</em> (seg sjølv)." },
    { prompt: "Vi møtte ___ på butikken.", cue: "(oss / kvarandre)", accept: ["kvarandre"], options: ["oss", "kverandre"], why: "Gjensidig: vi møtte <em class=\"nn\">kvarandre</em>. «Vi møtte oss» gir ikkje meining." },
    { prompt: "Ho gjorde det heilt ___.", cue: "(seg / sjølv)", accept: ["sjølv"], options: ["seg", "sjøl"], why: "<em class=\"nn\">sjølv</em> understrekar at ho gjorde det utan hjelp. Skriv <em class=\"nn\">sjølv</em> med v." },
    { prompt: "Eg måtte skrive heile teksten ___.", cue: "(meg / sjølv)", accept: ["sjølv"], options: ["meg", "selv"], why: "Understreking: <em class=\"nn\">sjølv</em>." },
    { prompt: "Barna kledde på ___.", cue: "(seg / dei)", accept: ["seg"], options: ["dei", "dem"], why: "Refleksivt: barna kledde på <em class=\"nn\">seg</em> (seg sjølve)." },
    { prompt: "Dei to snakkar aldri med ___.", cue: "(seg / kvarandre)", accept: ["kvarandre"], options: ["seg", "hverandre"], why: "Gjensidig: <em class=\"nn\">kvarandre</em>." },
  ],
};

if (typeof module !== "undefined" && module.exports) module.exports = Bank;
